

export const OPEN_DIALOG = 'CTRL_K_OPEN_DIALOG';
export const CLOSE_DIALOG = 'CTRL_K_CLOSE_DIALOG';
export const TOGGLE_DIALOG = 'CTRL_K_TOGGLE_DIALOG';

export const DIALOG_BORDER_RADIUS_SIZE = '0.652rem';